# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf8e44b8618a1f9fb2179e8fe9898e2761fded0150c851a4c40d7d500b2ead5e440340169d4521aef6d712d248e4a887b1c9c5b856dc39d258a511e1b426dafc

test:
  secret_key_base: a8b6da6a25272875f7acb0adf33ff47d3ed1a533b46c61a43eed0074fa2725de41bd03ea04317d36a74e329bc8b02b338b6e620803c9c019bed14caa24f61fbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
